config/routes.rb
Rails.application.routes.draw do
  scope '', module: 'admin', as: 'admin' do
    resources :driver_reports do
      get 'table', on: :collection
    end
    resources :weekly_reports do
      get 'table', on: :collection
    end
    resources :locations
    resources :drivers
    resources :trucks do
      resources :truck_logs, shallow: true
    end

    root to: redirect('/driver_reports')
  end

  namespace :api do
    resources :locations, only: %i(index)
    resources :drivers, only: %i(index)
    resources :trucks, only: %i(index)

    post 'report', to: 'driver_reports#create'
  end
end

app/models/truck.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: trucks
#
#  id         :integer          not null, primary key
#  identifier :string           default(""), not null
#  mileage    :decimal(, )      default(0.0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Truck < ApplicationRecord
  has_many :truck_logs

  validates :identifier, presence: true, uniqueness: true
  validates :mileage, presence: true, numericality: { greater_than_or_equal_to: 0 }

  after_create :create_weekly_report

  default_scope -> { order(:id) }

  def create_weekly_report
    WeeklyReport.create(
      truck: self,
      initial_mileage: mileage,
      current_mileage: mileage,
      total_gas: 0.0,
      total_paid: 0.0
    )
  end
end

app/controllers/admin/trucks_controller.rb
module Admin
  class TrucksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Truck.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Truck.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/trucks_controller.rb
module API
  class TrucksController < ApplicationController
    def index
      render json: Truck.all
    end
  end
end

app/views/admin/trucks/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
An instance of [Administrate::Page::Collection][1].
The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
the columns displayed in the table
- `resources`:
An ActiveModel::Relation collection of resources to be displayed in the table.
By default, the number of resources is limited by pagination
or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table class="collection-data" aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
      <th class="cell-label
      cell-label--<%= attr_type.html_class %>
      cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>" scope="col"
      >
      <%= t(
      "helpers.label.#{resource_name}.#{attr_name}",
      default: attr_name.to_s,
      ).titleize %>
    </th>
    <% end %>
    <th colspan="3" scope="col"></th>
  </tr>
</thead>

<tbody>
  <% if resources.count > 0 %>
    <% resources.each do |resource| %>
      <tr class="table__row" role="link" tabindex="0" data-url="<%= polymorphic_path([namespace, resource]) -%>">
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <td>
          <%= link_to( 'View logs', admin_truck_truck_logs_path(resource), class: "action-edit", ) %>
        </td>
        <td>
          <%= link_to( t("administrate.actions.edit"), [:edit, namespace, resource], class: "action-edit", ) %>
        </td>
        <td>
          <%= link_to(
          t("administrate.actions.delete"),
          [namespace, resource],
          class: "table__action--destroy",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
            ) %>
        </td>
      </tr>
    <% end %>

    <% else %>

    <tr class='table__row' tabindex="0" >
      <td class='no-elements' colspan='12'>
        There are no maintenance logs for this truck.
      </td>
    </tr>

    <% end %>
  </tbody>
</table>

app/views/admin/trucks/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { page.resource.identifier } %>

<header class="header">
  <h1 class="header__heading">
    <%= page.resource.identifier %>
  </h1>
  <div class="header__actions">
    <%= link_to(
      "Edit",
      [:edit, namespace, page.resource],
      class: "button",
    ) %>
  </div>
</header>

<dl>
  <% page.attributes.each do |attribute| %>
    <dt class="attribute-label">
    <%= t(
      "helpers.label.#{resource_name}.#{attribute.name}",
      default: attribute.name.titleize,
    ) %>
    </dt>

    <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
        ><%= render_field attribute %>
    </dd>
  <% end %>

  <dt class='attribute-label'></dt>
  <dd class='attribute-data'>
    <%= link_to 'View Logs', admin_truck_truck_logs_path(page.resource), class: 'button' %>
  </dd>

</dl>