config/routes.rb
Rails.application.routes.draw do
  scope '', module: 'admin', as: 'admin' do
    resources :driver_reports do
      get 'table', on: :collection
    end
    resources :weekly_reports do
      get 'table', on: :collection
    end
    resources :locations
    resources :drivers
    resources :trucks do
      resources :truck_logs, shallow: true
    end

    root to: redirect('/driver_reports')
  end

  namespace :api do
    resources :locations, only: %i(index)
    resources :drivers, only: %i(index)
    resources :trucks, only: %i(index)

    post 'report', to: 'driver_reports#create'
  end
end

app/models/truck_log.rb
# == Schema Information
#
# Table name: truck_logs
#
#  id           :integer          not null, primary key
#  truck_id     :integer
#  price        :decimal(, )
#  mileage      :decimal(, )
#  description  :text
#  performed_on :date
#

class TruckLog < ActiveRecord::Base
  belongs_to :truck

  validates_presence_of :price, :mileage, :truck, :performed_on

  default_scope -> { order(performed_on: :desc) }
end

app/controllers/admin/truck_logs_controller.rb
module Admin
  class TruckLogsController < Admin::ApplicationController
    before_action :find_truck, only: %i(index create)

    def index
      search_term = params[:search].to_s.strip
      resources = Administrate::Search.new(resource_resolver, search_term).run
      resources = resources.merge(@truck.truck_logs)
      resources = order.apply(resources)
      resources = resources.page(params[:page]).per(records_per_page)
      page = Administrate::Page::Collection.new(dashboard, order: order)

      render locals: {
        resources: resources,
        search_term: search_term,
        page: page,
      }
    end

    def create
      resource = @truck.truck_logs.new(resource_params)

      if resource.save
        redirect_to(
          admin_truck_log_path(resource),
          notice: 'Truck Log was successfully created.'
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource),
        }
      end
    end

    def destroy
      requested_resource.destroy
      flash[:notice] = translate_with_resource("destroy.success")
      redirect_to admin_truck_truck_logs_path(requested_resource.truck)
    end

    def find_truck
      @truck = Truck.find(params[:truck_id])
    end
  end
end

app/views/admin/truck_logs/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
An instance of [Administrate::Page::Collection][1].
The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
the columns displayed in the table
- `resources`:
An ActiveModel::Relation collection of resources to be displayed in the table.
By default, the number of resources is limited by pagination
or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table class="collection-data" aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
      <th class="cell-label
      cell-label--<%= attr_type.html_class %>
      cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>" scope="col"
      >
      <%= t(
      "helpers.label.#{resource_name}.#{attr_name}",
      default: attr_name.to_s,
      ).titleize %>
    </th>
    <% end %>
    <th colspan="2" scope="col"></th>
  </tr>
</thead>

<tbody>
  <% if resources.count > 0 %>
    <% resources.each do |resource| %>
      <tr class="table__row" role="link" tabindex="0" data-url="<%= polymorphic_path([namespace, resource]) -%>">
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <td>
          <%= link_to( t("administrate.actions.edit"), [:edit, namespace, resource], class: "action-edit", ) %>
        </td>
        <td>
          <%= link_to(
          t("administrate.actions.delete"),
          [namespace, resource],
          class: "table__action--destroy",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
            ) %>
        </td>
      </tr>
    <% end %>

    <% else %>

    <tr class='table__row' tabindex="0" >
      <td class='no-elements' colspan='12'>
        There are no maintenance logs for this truck.
      </td>
    </tr>

    <% end %>
  </tbody>
</table>

app/views/admin/truck_logs/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([:admin, Truck.find_by_id(params[:truck_id]), page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(page.resource.errors.count, "error") %>
        prohibited this <%= page.resource_name %> from being saved:
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/truck_logs/index.html.erb
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="header">
  <h1 class="header__heading" id="page-title">
    <%= link_to(Truck.find_by_id(params[:truck_id])&.identifier, admin_truck_path(params[:truck_id])) %>
    -
    Logs
  </h1>
  <div class="header__actions">
  <%= link_to(
    "New #{page.resource_name.titleize.downcase}",
    new_admin_truck_truck_log_path(params[:truck_id]),
    class: "button",
  ) %>
</div>
</header>

<div class='table-wrapper'>
  <%= render "collection", collection_presenter: page, resources: resources %>
</div>

app/views/admin/truck_logs/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "New Truck Log" } %>

<header class="header">
  <h1 class="header__heading"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to 'Back', :back, class: "button" %>
  </div>
</header>

<%= render 'form', page: page %>

app/views/admin/truck_logs/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { page.resource.performed_on } %>

<header class="header">
  <h1 class="header__heading">
    <%= page.resource.performed_on %>
  </h1>
  <div class="header__actions">
    <%= link_to(
      "Index",
      admin_truck_truck_logs_path(page.resource.truck),
      class: "button",
    ) %>
    <%= link_to(
      "Edit",
      [:edit, namespace, page.resource],
      class: "button",
    ) %>
  </div>
</header>

<dl>
  <% page.attributes.each do |attribute| %>
    <dt class="attribute-label">
    <%= t(
      "helpers.label.#{resource_name}.#{attribute.name}",
      default: attribute.name.titleize,
    ) %>
    </dt>

    <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
        ><%= render_field attribute %></dd>
  <% end %>
</dl>